name: vibestream
description: "VibeStream - Discover movies and series based on your mood"
publish_to: "none"

version: 1.0.0+13

environment:
  sdk: ^3.6.0
dependencies:
  purchases_ui_flutter: ^9.0.0
  purchases_flutter: ^9.0.0
  mixpanel_flutter: ^2.0.0
  country_picker: ^2.0.0
  google_sign_in: '^6.2.1'
  crypto: ^3.0.0
  sign_in_with_apple: '>=6.1.2'
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^14.2.7
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  cached_network_image: ^3.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.0
  supabase_flutter: ^2.6.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
